---
platform: linux
image_resource:
  type: docker-image
  # source: 
  #   repository: hashicorp/terraform
  #   tag: 0.11.14
params:
  STATE_BUCKET_SECRET_KEY:
  # - Required
  # - Minio Secret
  STATE_BUCKET_KEY_ID:
  # - Required
  # - Minio Access Key
  STATE_BUCKET:
  # - Required
  # - Bucket where tf state will be stored
  FOUNDATION:
  # - Required
  # - Name of foundation to be used to locate vars and label the state file
  PRODUCT:
  # - Required
  # pas or pks, lower case only
  S3_ENDPOINT:
  # - Required
  # - URL of the Minio endpoint
  TF_VAR_aws_access_key:
  # - Required
  # - cloud client id
  TF_VAR_aws_secret_key:
  # - cloud client secret


inputs:
- name: config
- name: terraform
- name: generated-tf-output

run:
  path: config/tasks/terraform-aws-dns/task.sh