---
platform: linux
image_resource:
  type: docker-image

inputs:
- name: config
- name: state
- name: s5cmd

outputs:
- name: tf-state
- name: state

params:
  CLOUD_CREDS:
  IAAS_TYPE:
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  S3_ENDPOINT: 
  FOUNDATION: 

run:
  path: config/tasks/wipe-vsphere-vms/task.sh